# Schema for the configuration files of the Lark module.
lark.settings:
  type: config_object
  label: 'Lark settings'
  mapping:
    default_source:
      type: string
      label: 'Default Source'
    ignored_comparison_keys:
      type: string
      label: 'Ignored Comparison Keys'
    should_export_assets:
      type: string
      label: 'Default export action'
    asset_export_file_exists:
      type: string
      label: 'Default export conflict action'
    should_import_assets:
      type: string
      label: 'Default import action'
    asset_import_file_exists:
      type: string
      label: 'Default import conflict action'
